image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - init: >
      composer install --prefer-source -n
      vendor/bin/blt alias --no-interaction
      source ~/.bashrc
