ports:
  - port: 3306
    onOpen: ignore
  - port: 33060
    onOpen: ignore
  - port: 8001
    onOpen: open-preview
image:
  file: .gitpod/Dockerfile
tasks:
  - init: chmod +x .gitpod/init.sh && .gitpod/init.sh